/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_COMMA = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_COLON = 6,
  anon_sym_DQUOTE = 7,
  sym_string_content = 8,
  sym_escape_quote = 9,
  sym_escape_sequence = 10,
  sym_number = 11,
  sym_true = 12,
  sym_false = 13,
  sym_null = 14,
  sym_cell_type_key = 15,
  sym_execution_count_key = 16,
  sym_id_key = 17,
  sym_metadata_key = 18,
  sym_outputs_key = 19,
  sym_source_key = 20,
  sym_output_type_key = 21,
  sym_data_key = 22,
  sym_name_key = 23,
  sym_text_key = 24,
  sym_ename_key = 25,
  sym_evalue_key = 26,
  sym_traceback_key = 27,
  sym_cell_type_code = 28,
  sym_cell_type_markdown = 29,
  sym_cell_type_raw = 30,
  sym_source_file = 31,
  sym__value = 32,
  sym_object = 33,
  sym_array = 34,
  sym_pair = 35,
  sym__key = 36,
  sym_cell = 37,
  sym_code_cell = 38,
  sym_markdown_cell = 39,
  sym_raw_cell = 40,
  sym_string = 41,
  aux_sym_object_repeat1 = 42,
  aux_sym_array_repeat1 = 43,
  aux_sym_string_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_escape_quote] = "escape_quote",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_cell_type_key] = "cell_type_key",
  [sym_execution_count_key] = "execution_count_key",
  [sym_id_key] = "id_key",
  [sym_metadata_key] = "metadata_key",
  [sym_outputs_key] = "outputs_key",
  [sym_source_key] = "source_key",
  [sym_output_type_key] = "output_type_key",
  [sym_data_key] = "data_key",
  [sym_name_key] = "name_key",
  [sym_text_key] = "text_key",
  [sym_ename_key] = "ename_key",
  [sym_evalue_key] = "evalue_key",
  [sym_traceback_key] = "traceback_key",
  [sym_cell_type_code] = "cell_type_code",
  [sym_cell_type_markdown] = "cell_type_markdown",
  [sym_cell_type_raw] = "cell_type_raw",
  [sym_source_file] = "source_file",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_pair] = "pair",
  [sym__key] = "_key",
  [sym_cell] = "cell",
  [sym_code_cell] = "code_cell",
  [sym_markdown_cell] = "markdown_cell",
  [sym_raw_cell] = "raw_cell",
  [sym_string] = "string",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_escape_quote] = sym_escape_quote,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_cell_type_key] = sym_cell_type_key,
  [sym_execution_count_key] = sym_execution_count_key,
  [sym_id_key] = sym_id_key,
  [sym_metadata_key] = sym_metadata_key,
  [sym_outputs_key] = sym_outputs_key,
  [sym_source_key] = sym_source_key,
  [sym_output_type_key] = sym_output_type_key,
  [sym_data_key] = sym_data_key,
  [sym_name_key] = sym_name_key,
  [sym_text_key] = sym_text_key,
  [sym_ename_key] = sym_ename_key,
  [sym_evalue_key] = sym_evalue_key,
  [sym_traceback_key] = sym_traceback_key,
  [sym_cell_type_code] = sym_cell_type_code,
  [sym_cell_type_markdown] = sym_cell_type_markdown,
  [sym_cell_type_raw] = sym_cell_type_raw,
  [sym_source_file] = sym_source_file,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_pair] = sym_pair,
  [sym__key] = sym__key,
  [sym_cell] = sym_cell,
  [sym_code_cell] = sym_code_cell,
  [sym_markdown_cell] = sym_markdown_cell,
  [sym_raw_cell] = sym_raw_cell,
  [sym_string] = sym_string,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_cell_type_key] = {
    .visible = true,
    .named = true,
  },
  [sym_execution_count_key] = {
    .visible = true,
    .named = true,
  },
  [sym_id_key] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_key] = {
    .visible = true,
    .named = true,
  },
  [sym_outputs_key] = {
    .visible = true,
    .named = true,
  },
  [sym_source_key] = {
    .visible = true,
    .named = true,
  },
  [sym_output_type_key] = {
    .visible = true,
    .named = true,
  },
  [sym_data_key] = {
    .visible = true,
    .named = true,
  },
  [sym_name_key] = {
    .visible = true,
    .named = true,
  },
  [sym_text_key] = {
    .visible = true,
    .named = true,
  },
  [sym_ename_key] = {
    .visible = true,
    .named = true,
  },
  [sym_evalue_key] = {
    .visible = true,
    .named = true,
  },
  [sym_traceback_key] = {
    .visible = true,
    .named = true,
  },
  [sym_cell_type_code] = {
    .visible = true,
    .named = true,
  },
  [sym_cell_type_markdown] = {
    .visible = true,
    .named = true,
  },
  [sym_cell_type_raw] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__key] = {
    .visible = false,
    .named = true,
  },
  [sym_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_code_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_type = 2,
  field_type_key = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_type] = "type",
  [field_type_key] = "type_key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
  [2] =
    {field_type, 3},
    {field_type_key, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(122);
      ADVANCE_MAP(
        '"', 130,
        ',', 124,
        '-', 22,
        '0', 135,
        ':', 128,
        '[', 126,
        '\\', 2,
        ']', 127,
        'f', 26,
        'n', 102,
        't', 88,
        '{', 123,
        '}', 125,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(121);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(17);
      if (lookahead == '"') ADVANCE(129);
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(131);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 133,
        'u', 120,
        '/', 134,
        '\\', 134,
        'b', 134,
        'f', 134,
        'n', 134,
        'r', 134,
        't', 134,
      );
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(144);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(149);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(150);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(151);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(152);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(153);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(147);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(146);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(145);
      END_STATE();
    case 12:
      if (lookahead == '"') ADVANCE(142);
      END_STATE();
    case 13:
      if (lookahead == '"') ADVANCE(154);
      END_STATE();
    case 14:
      if (lookahead == '"') ADVANCE(148);
      END_STATE();
    case 15:
      if (lookahead == '"') ADVANCE(143);
      END_STATE();
    case 16:
      ADVANCE_MAP(
        '"', 129,
        ',', 124,
        '-', 22,
        '0', 135,
        '[', 126,
        ']', 127,
        'f', 26,
        'n', 102,
        't', 88,
        '{', 123,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 17:
      if (lookahead == '"') ADVANCE(129);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      END_STATE();
    case 18:
      if (lookahead == '"') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      END_STATE();
    case 19:
      if (lookahead == '"') ADVANCE(157);
      END_STATE();
    case 20:
      if (lookahead == '"') ADVANCE(155);
      END_STATE();
    case 21:
      if (lookahead == '"') ADVANCE(156);
      END_STATE();
    case 22:
      if (lookahead == '0') ADVANCE(135);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 23:
      if (lookahead == '_') ADVANCE(92);
      END_STATE();
    case 24:
      if (lookahead == '_') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == '_') ADVANCE(100);
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(96);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(110);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(87);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 35:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(98);
      END_STATE();
    case 39:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(66);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(81);
      if (lookahead == 'm') ADVANCE(33);
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(54);
      END_STATE();
    case 43:
      if (lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(83);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(106);
      END_STATE();
    case 46:
      if (lookahead == 'd') ADVANCE(3);
      END_STATE();
    case 47:
      if (lookahead == 'd') ADVANCE(80);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 49:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(111);
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(139);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(140);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 64:
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 65:
      if (lookahead == 'k') ADVANCE(47);
      END_STATE();
    case 66:
      if (lookahead == 'k') ADVANCE(13);
      END_STATE();
    case 67:
      if (lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 68:
      if (lookahead == 'l') ADVANCE(141);
      END_STATE();
    case 69:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 70:
      if (lookahead == 'l') ADVANCE(68);
      END_STATE();
    case 71:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 72:
      if (lookahead == 'l') ADVANCE(108);
      END_STATE();
    case 73:
      if (lookahead == 'm') ADVANCE(55);
      END_STATE();
    case 74:
      if (lookahead == 'm') ADVANCE(56);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 76:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 77:
      if (lookahead == 'n') ADVANCE(37);
      if (lookahead == 'v') ADVANCE(35);
      if (lookahead == 'x') ADVANCE(51);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(99);
      END_STATE();
    case 79:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 80:
      if (lookahead == 'o') ADVANCE(109);
      END_STATE();
    case 81:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 82:
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 83:
      if (lookahead == 'o') ADVANCE(104);
      END_STATE();
    case 84:
      if (lookahead == 'p') ADVANCE(59);
      END_STATE();
    case 85:
      if (lookahead == 'p') ADVANCE(60);
      END_STATE();
    case 86:
      if (lookahead == 'p') ADVANCE(107);
      END_STATE();
    case 87:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 88:
      if (lookahead == 'r') ADVANCE(105);
      END_STATE();
    case 89:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 90:
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 92:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 94:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 95:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 96:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 97:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 98:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 99:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 100:
      if (lookahead == 't') ADVANCE(113);
      END_STATE();
    case 101:
      if (lookahead == 'u') ADVANCE(89);
      END_STATE();
    case 102:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 103:
      if (lookahead == 'u') ADVANCE(91);
      END_STATE();
    case 104:
      if (lookahead == 'u') ADVANCE(78);
      END_STATE();
    case 105:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 106:
      if (lookahead == 'u') ADVANCE(93);
      END_STATE();
    case 107:
      if (lookahead == 'u') ADVANCE(94);
      END_STATE();
    case 108:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 109:
      if (lookahead == 'w') ADVANCE(76);
      END_STATE();
    case 110:
      if (lookahead == 'w') ADVANCE(19);
      END_STATE();
    case 111:
      if (lookahead == 'x') ADVANCE(95);
      END_STATE();
    case 112:
      if (lookahead == 'y') ADVANCE(84);
      END_STATE();
    case 113:
      if (lookahead == 'y') ADVANCE(85);
      END_STATE();
    case 114:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 115:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 116:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 117:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(134);
      END_STATE();
    case 118:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(117);
      END_STATE();
    case 119:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(118);
      END_STATE();
    case 120:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(119);
      END_STATE();
    case 121:
      if (eof) ADVANCE(122);
      ADVANCE_MAP(
        '"', 130,
        ',', 124,
        '-', 22,
        '0', 135,
        ':', 128,
        '[', 126,
        ']', 127,
        'f', 26,
        'n', 102,
        't', 88,
        '{', 123,
        '}', 125,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(121);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      ADVANCE_MAP(
        'c', 63,
        'd', 27,
        'e', 77,
        'i', 46,
        'm', 62,
        'n', 28,
        'o', 103,
        's', 82,
        't', 50,
      );
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(131);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(132);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_escape_quote);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(115);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(114);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(115);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_cell_type_key);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_execution_count_key);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_id_key);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_metadata_key);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_outputs_key);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_source_key);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_output_type_key);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_data_key);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_name_key);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_text_key);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_ename_key);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_evalue_key);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_traceback_key);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_cell_type_code);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_cell_type_markdown);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_cell_type_raw);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 16},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_quote] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_cell_type_key] = ACTIONS(1),
    [sym_execution_count_key] = ACTIONS(1),
    [sym_id_key] = ACTIONS(1),
    [sym_metadata_key] = ACTIONS(1),
    [sym_outputs_key] = ACTIONS(1),
    [sym_source_key] = ACTIONS(1),
    [sym_output_type_key] = ACTIONS(1),
    [sym_data_key] = ACTIONS(1),
    [sym_name_key] = ACTIONS(1),
    [sym_text_key] = ACTIONS(1),
    [sym_ename_key] = ACTIONS(1),
    [sym_evalue_key] = ACTIONS(1),
    [sym_traceback_key] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(50),
    [sym__value] = STATE(56),
    [sym_object] = STATE(56),
    [sym_array] = STATE(56),
    [sym_cell] = STATE(56),
    [sym_code_cell] = STATE(28),
    [sym_markdown_cell] = STATE(28),
    [sym_raw_cell] = STATE(28),
    [sym_string] = STATE(56),
    [anon_sym_LBRACE] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [sym_true] = ACTIONS(9),
    [sym_false] = ACTIONS(9),
    [sym_null] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_object_repeat1,
    STATE(49), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(17), 13,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [35] = 7,
    ACTIONS(19), 1,
      anon_sym_COMMA,
    ACTIONS(22), 1,
      anon_sym_RBRACE,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_object_repeat1,
    STATE(52), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(27), 13,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [70] = 7,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(30), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      aux_sym_object_repeat1,
    STATE(48), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(17), 13,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [105] = 7,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(32), 1,
      anon_sym_COMMA,
    ACTIONS(34), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      aux_sym_object_repeat1,
    STATE(40), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(17), 13,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [140] = 7,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      aux_sym_object_repeat1,
    STATE(47), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(17), 13,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [175] = 7,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(38), 1,
      anon_sym_COMMA,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_object_repeat1,
    STATE(41), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(17), 13,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [210] = 8,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(42), 1,
      anon_sym_COMMA,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    ACTIONS(46), 1,
      sym_cell_type_key,
    STATE(4), 1,
      aux_sym_object_repeat1,
    STATE(45), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(17), 12,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [247] = 7,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(48), 1,
      anon_sym_COMMA,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_object_repeat1,
    STATE(44), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(17), 13,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [282] = 7,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      aux_sym_object_repeat1,
    STATE(39), 1,
      sym_pair,
    STATE(54), 2,
      sym__key,
      sym_string,
    ACTIONS(17), 13,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [317] = 9,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(56), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      aux_sym_array_repeat1,
    STATE(28), 3,
      sym_code_cell,
      sym_markdown_cell,
      sym_raw_cell,
    ACTIONS(58), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(43), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_cell,
      sym_string,
  [354] = 9,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      anon_sym_RBRACK,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_array_repeat1,
    STATE(28), 3,
      sym_code_cell,
      sym_markdown_cell,
      sym_raw_cell,
    ACTIONS(74), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(55), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_cell,
      sym_string,
  [391] = 9,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    ACTIONS(79), 1,
      anon_sym_RBRACK,
    STATE(11), 1,
      aux_sym_array_repeat1,
    STATE(28), 3,
      sym_code_cell,
      sym_markdown_cell,
      sym_raw_cell,
    ACTIONS(81), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(46), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_cell,
      sym_string,
  [428] = 2,
    ACTIONS(83), 1,
      anon_sym_DQUOTE,
    ACTIONS(22), 15,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_cell_type_key,
      sym_execution_count_key,
      sym_id_key,
      sym_metadata_key,
      sym_outputs_key,
      sym_source_key,
      sym_output_type_key,
      sym_data_key,
      sym_name_key,
      sym_text_key,
      sym_ename_key,
      sym_evalue_key,
      sym_traceback_key,
  [449] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    STATE(28), 3,
      sym_code_cell,
      sym_markdown_cell,
      sym_raw_cell,
    ACTIONS(85), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(42), 5,
      sym__value,
      sym_object,
      sym_array,
      sym_cell,
      sym_string,
  [477] = 1,
    ACTIONS(69), 9,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [489] = 1,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_COLON,
  [497] = 3,
    ACTIONS(89), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      aux_sym_string_repeat1,
    ACTIONS(91), 3,
      sym_string_content,
      sym_escape_quote,
      sym_escape_sequence,
  [509] = 3,
    ACTIONS(93), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      aux_sym_string_repeat1,
    ACTIONS(95), 3,
      sym_string_content,
      sym_escape_quote,
      sym_escape_sequence,
  [521] = 3,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      aux_sym_string_repeat1,
    ACTIONS(99), 3,
      sym_string_content,
      sym_escape_quote,
      sym_escape_sequence,
  [533] = 1,
    ACTIONS(102), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_COLON,
  [541] = 1,
    ACTIONS(104), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [548] = 1,
    ACTIONS(106), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [555] = 1,
    ACTIONS(108), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [562] = 1,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [569] = 1,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [576] = 1,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [583] = 1,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [590] = 1,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [597] = 1,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [604] = 1,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [611] = 1,
    ACTIONS(124), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [618] = 1,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [625] = 1,
    ACTIONS(128), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [632] = 1,
    ACTIONS(130), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [639] = 1,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [646] = 1,
    ACTIONS(134), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [653] = 3,
    ACTIONS(136), 1,
      sym_cell_type_code,
    ACTIONS(138), 1,
      sym_cell_type_markdown,
    ACTIONS(140), 1,
      sym_cell_type_raw,
  [663] = 2,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
  [670] = 2,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    ACTIONS(142), 1,
      anon_sym_COMMA,
  [677] = 2,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(142), 1,
      anon_sym_COMMA,
  [684] = 1,
    ACTIONS(146), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [689] = 2,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    ACTIONS(150), 1,
      anon_sym_RBRACK,
  [696] = 2,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(142), 1,
      anon_sym_COMMA,
  [703] = 2,
    ACTIONS(30), 1,
      anon_sym_RBRACE,
    ACTIONS(142), 1,
      anon_sym_COMMA,
  [710] = 2,
    ACTIONS(56), 1,
      anon_sym_RBRACK,
    ACTIONS(148), 1,
      anon_sym_COMMA,
  [717] = 2,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
  [724] = 2,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
  [731] = 2,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
  [738] = 1,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
  [742] = 1,
    ACTIONS(160), 1,
      anon_sym_COMMA,
  [746] = 1,
    ACTIONS(142), 1,
      anon_sym_COMMA,
  [750] = 1,
    ACTIONS(162), 1,
      anon_sym_COLON,
  [754] = 1,
    ACTIONS(165), 1,
      anon_sym_COLON,
  [758] = 1,
    ACTIONS(148), 1,
      anon_sym_COMMA,
  [762] = 1,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
  [766] = 1,
    ACTIONS(169), 1,
      anon_sym_COMMA,
  [770] = 1,
    ACTIONS(171), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 175,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 247,
  [SMALL_STATE(10)] = 282,
  [SMALL_STATE(11)] = 317,
  [SMALL_STATE(12)] = 354,
  [SMALL_STATE(13)] = 391,
  [SMALL_STATE(14)] = 428,
  [SMALL_STATE(15)] = 449,
  [SMALL_STATE(16)] = 477,
  [SMALL_STATE(17)] = 489,
  [SMALL_STATE(18)] = 497,
  [SMALL_STATE(19)] = 509,
  [SMALL_STATE(20)] = 521,
  [SMALL_STATE(21)] = 533,
  [SMALL_STATE(22)] = 541,
  [SMALL_STATE(23)] = 548,
  [SMALL_STATE(24)] = 555,
  [SMALL_STATE(25)] = 562,
  [SMALL_STATE(26)] = 569,
  [SMALL_STATE(27)] = 576,
  [SMALL_STATE(28)] = 583,
  [SMALL_STATE(29)] = 590,
  [SMALL_STATE(30)] = 597,
  [SMALL_STATE(31)] = 604,
  [SMALL_STATE(32)] = 611,
  [SMALL_STATE(33)] = 618,
  [SMALL_STATE(34)] = 625,
  [SMALL_STATE(35)] = 632,
  [SMALL_STATE(36)] = 639,
  [SMALL_STATE(37)] = 646,
  [SMALL_STATE(38)] = 653,
  [SMALL_STATE(39)] = 663,
  [SMALL_STATE(40)] = 670,
  [SMALL_STATE(41)] = 677,
  [SMALL_STATE(42)] = 684,
  [SMALL_STATE(43)] = 689,
  [SMALL_STATE(44)] = 696,
  [SMALL_STATE(45)] = 703,
  [SMALL_STATE(46)] = 710,
  [SMALL_STATE(47)] = 717,
  [SMALL_STATE(48)] = 724,
  [SMALL_STATE(49)] = 731,
  [SMALL_STATE(50)] = 738,
  [SMALL_STATE(51)] = 742,
  [SMALL_STATE(52)] = 746,
  [SMALL_STATE(53)] = 750,
  [SMALL_STATE(54)] = 754,
  [SMALL_STATE(55)] = 758,
  [SMALL_STATE(56)] = 762,
  [SMALL_STATE(57)] = 766,
  [SMALL_STATE(58)] = 770,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 7, 1, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_cell, 8, 1, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 6, 1, 2),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 6, 1, 2),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 7, 1, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_cell, 6, 1, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_cell, 7, 1, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 8, 1, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 8, 1, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [158] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__key, 1, 0, 0), SHIFT(38),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ipynb_notebook(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ipynb_notebook",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
